# Generated by Django 2.0.7 on 2018-11-16 13:33

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('boss_echarts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='refined_boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateField()),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('raw_boss', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='boss_echarts.Boss')),
            ],
            options={
                'db_table': 'refined_boss',
                'managed': True,
            },
        ),
    ]
