# Generated by Django 2.0.7 on 2018-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss_echarts', '0002_refined_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='refined_boss',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
