# Generated by Django 2.0.7 on 2018-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss_echarts', '0003_refined_boss_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='refined_boss',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
